### ISSUE TITLE
When using Raik, it would be sweet to not use "/" in key names

### ISSUE THREAD

**Issue by evantahler** [taskrabbit/storehouse#3]
When using some http clients (including a browser), Riak assumes "/" is a route rather than a key.  For example:

`https://localhost:8000/buckets/page_cache/keys/#{sha}::#{rails_env}::/path/page` returns `Invalid link walk query submitted. Valid link walk query format is: /riak/some_bucket/some_key/<bucket>,<riaktag>,0|1/...`

Perhaps a little HTML encoding http://lists.basho.com/pipermail/riak-users_lists.basho.com/2010-February/000621.html or some other character would work `path = path.gsub("\", "~")`

**Comment by scalp42** [comment]
I think the correct approach to url encode it :

`/` -> `%2F`

Riak will correctly convert it to `/`

**Comment by scalp42** [comment]
nice buddy!
